#!name=Bilibili
#!desc=Bilibili

[URL Rewrite]

# ～ BiliBili_哔哩哔哩_屏蔽广告浮窗
^https?:\/\/api\.bilibili\.com\/pgc\/activity\/deliver\/material\/receive - reject-dict
# ～ BiliBili_哔哩哔哩_Material_Ad
^https?:\/\/api\.bilibili\.com\/x\/vip\/ads\/material\/report - reject-dict
# ～ BiliBili_哔哩哔哩_小卡片广告
^https://api.bilibili.com/pgc/season/player/cards - reject-dict
# ～ BiliBili_哔哩哔哩_屏蔽IP请求
^https?:\/\/app\.bilibili\.com\/x\/resource\/ip - reject
# ～ BiliBili_哔哩哔哩_应用开屏去广告
^https://app.bilibili.com/x/v2/splash/show - reject-dict
# ～ BiliBili_哔哩哔哩_漫画去广告
^https?:\/\/manga\.bilibili\.com\/twirp\/comic\.v\d\.Comic\/(Flash|ListFlash|GetActivityTab) - reject-dict
# ～ BiliBili_哔哩哔哩_屏蔽DefaultWord@ddgksf2013
^https?:\/\/(app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.interface\.v1\.Search\/Default - reject

[Script]

# ～ BiliBili_哔哩哔哩_视频播放下方商品推广
bilibili_json_92 = type=http-response, pattern=^https?:\/\/api\.bili(api|bili)\.(net|com)\/pgc\/season\/app\/related\/recommend\?, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_屏蔽直播间商品广告浮窗[还有一个域名]
bilibili_json_95 = type=http-response, pattern=^https?:\/\/api\.live\.bilibili\.com\/xlive\/e-commerce-interface\/v\d\/ecommerce-user\/get_shopping_info\?, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_直播去广告
bilibili_json_97 = type=http-response, pattern=^https?:\/\/api\.live\.bilibili\.com\/xlive\/app-room\/v1\/index\/getInfoByRoom, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_应用开屏广告预加载
bilibili_json_104 = type=http-response, pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/splash\/list, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_1080P高码率+4K画质[番剧和影视除外]
bilibili_json_107 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/myinfo\?, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_屏蔽直播页顶部轮播图
bilibili_json_110 = type=http-response, pattern=^https?:\/\/api\.live\.bilibili\.com\/xlive\/app-interface\/v2\/index\/feed, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_推荐去广告
bilibili_json_114 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/feed\/index, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_追番去广告
bilibili_json_116 = type=http-response, pattern=^https?:\/\/api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/bangumi, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_观影页面去广告
bilibili_json_118 = type=http-response, pattern=^https?:\/\/api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/cinema\/tab\?, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_标签页处理
bilibili_json_121 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/tab, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_我的页面处理
bilibili_json_123 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/mine, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_屏蔽首页右上活动
bilibili_json_125 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/top\/activity, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_热搜发现
bilibili_json_127 = type=http-response, pattern=^https://app.bilibili.com/x/v2/search/square, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_搜索去广告
BiliBili.ADBlock.response_132 = type=http-response, pattern=^https?:\/\/(grpc\.biliapi\.net|app\.bilibili\.com)\/bilibili\.polymer\.app\.search\.v1\.Search\/SearchAll$, requires-body=true, max-size=3145728, binary-body-mode=true, script-path=https://raw.githubusercontent.com/BiliUniverse/ADBlock/main/js/BiliBili.ADBlock.response.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_交互点赞投票弹幕
BiliBili.ADBlock.response.beta_134 = type=http-response, pattern=^https?:\/\/(app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.community\.service\.dm\.v1\.DM\/DmView, requires-body=true, max-size=3145728, binary-body-mode=true, script-path=https://raw.githubusercontent.com/BiliUniverse/ADBlock/beta/js/BiliBili.ADBlock.response.beta.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_青少年弹窗
BiliBili.ADBlock.response_136 = type=http-response, pattern=^https:\/\/(grpc\.biliapi\.net|app\.bilibili\.com)\/bilibili\.app\.interface\.v1\.Teenagers\/ModeStatus, requires-body=true, max-size=3145728, binary-body-mode=true, script-path=https://raw.githubusercontent.com/BiliUniverse/ADBlock/main/js/BiliBili.ADBlock.response.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_UP主推荐广告[适配ipad端]
bilibili_proto_138 = type=http-response, pattern=^https?:\/\/(app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.view\.v1\.View\/View$, requires-body=true, max-size=3145728, binary-body-mode=true, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_proto.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_动态页面去广告
bilibili_proto_140 = type=http-response, pattern=^https?:\/\/(app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.dynamic\.v2\.Dynamic\/DynAll$, requires-body=true, max-size=3145728, binary-body-mode=true, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_proto.js, timeout=60, script-update-interval=0

# ～ BiliBili_哔哩哔哩_启动时开启直连模式[自行启用]
#bilibili_startup_direct_143 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/domain, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_startup_direct.js, timeout=60, script-update-interval=0
# ～ BiliBili_哔哩哔哩_繁体CC字幕转中文简体[自行启用hostname=aisubtitle.hdslb.com,i0.hdslb.com]
#bilibili_cc_145 = type=http-response, pattern=^https?:\/\/.*\.hdslb\.com\/bfs\/subtitle\/.+\.json, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_cc.js, timeout=60, script-update-interval=0
# ～ BiliBili_哔哩哔哩_去除统一设置的皮肤[注释留存]
#bilibili_json_147 = type=http-response, pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/skin\?, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/bilibili_json.js, timeout=60, script-update-interval=0

[MITM]

hostname = %APPEND% -broadcast.chat.bilibili.com,-*cdn*.biliapi.net,-*tracker*.biliapi.net,app.bilibili.com,api.live.bilibili.com,*.bilibili.com,*.bilibili.*,grpc.biliapi.net,*biliapi.net