#!name=WeChat
#!desc=WeChat

[Script]

# > 微信去广告[不包含公众号信息流AD、朋友圈AD]
replaceBody_10 = type=http-response, pattern=^https?:\/\/mp\.weixin\.qq\.com\/mp\/getappmsgad, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/replace-body.js, timeout=60, argument="advertisement->ddgksf2013"

UnblockURLinWeChat_2 = type=http-response, pattern=^https\:\/\/(weixin110\.qq|security.wechat)\.com\/cgi-bin\/mmspamsupport-bin\/newredirectconfirmcgi\?, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/asset/UnblockURLinWeChat.js, timeout=60, script-update-interval=0

[MITM]

hostname = %APPEND% wxa.wxs.qq.com,mp.weixin.qq.com,weixin110.qq.com,security.wechat.com
