#!name=GDmap
#!desc=高德地图   去广告

[URL Rewrite]

# > 高德地图_路线规划下方广告@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/faas\/amap-navigation\/card-service-route-plan\? - reject-dict
# > 高德地图_Tip请求@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/boss\/order_web\/\w{8}_information - reject-200
# > 高德地图_通用广告请求@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/asa\/ads_attribution - reject
# > 高德地图_搜索框scene@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/shield\/scene\/recommend - reject-dict
# > 高德地图_首页左上角gif@ddgksf2013
^https?:\/\/.*\.amap\.com\/uploadimg\/\w+\.gif - reject-img
# > 高德地图_左下天气@ddgksf2013
^https?:\/\/.*\.amap\.com\/ws\/valueadded\/weather - reject-dict

[Script]

# > 高德地图_amdc处理[Anti已将Amdc分流删除,故更换屏蔽策略]@ddgksf2013
amdc_17 = type=http-response, pattern=^http:\/\/amdc\.m\.taobao\.com, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amdc.js, timeout=60, script-update-interval=0

# > 高德地图_底部tab栏角标@ddgksf2013
amap_19 = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/message\/notice\/list, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, timeout=60, script-update-interval=0

# > 高德地图_首页右中广告@ddgksf2013
amap_23 = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/shield\/frogserver\/aocs\/updatable, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, timeout=60, script-update-interval=0

# > 高德地图_附近页面@ddgksf2013
amap_25 = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/shield\/search\/nearbyrec_smart, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, timeout=60, script-update-interval=0

# > 高德地图_打车页面处理@ddgksf2013
amap_27 = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/promotion-web\/resource, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, timeout=60, script-update-interval=0

# > 高德地图_首页底部处理@ddgksf2013
amap_31 = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/faas\/amap-navigation\/main-page, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, timeout=60, script-update-interval=0

# > 高德地图_开屏广告@ddgksf2013
amap_35 = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/valueadded\/alimama\/splash_screen, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, timeout=60, script-update-interval=0

# > 高德地图_首页顶部推广@ddgksf2013
amap_37 = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/msgbox\/pull, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, timeout=60, script-update-interval=0

# > 高德地图_我的页面@ddgksf2013
amap_39 = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/shield\/dsp\/profile\/index\/nodefaas, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, timeout=60, script-update-interval=0

# > 高德地图_搜索框热词@ddgksf2013
amap_41 = type=http-response, pattern=^https?:\/\/.*\.amap\.com\/ws\/shield\/search\/new_hotword, requires-body=true, max-size=3145728, script-path=https://github.com/ddgksf2013/Scripts/raw/master/amap.js, timeout=60, script-update-interval=0

[MITM]

hostname = %APPEND% *.amap.com
